# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1117214c17c4e7e3ab3667a8c149abda9c2a8e28173eba8fadd272bedc3d4e8c77eb75ab90476bc2325fd3da85e94e27006b3c124a0c9e41ae82b6f49d65576

test:
  secret_key_base: 948e93afe08fd0c59cc079ad43e6e2ca8b4228245abf10789bf1318f782cc76c8e7e153466e6630947081fc7d926deefb4123d9783eb7c4de5b9a6bae7584cd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
